version: '3.8'

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-khorunzhyi}"
    image: pytorch_end_to_end
    container_name: pytorch_end_to_end-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-khorunzhyi}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app 
    volumes:
      - ./:/app/
      - ~/.config/gcloud:/home/${USER_NAME}/.config/gcloud
      - ./.ssh:/home/${USER_NAME}./ssh
    ports:
      - 8888:8888
    ipc: host
    init: true