services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-khorunzhyi}"
    image: rnn-sequence-classification-platform
    container_name: rnn-sequence-classification-platform-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-khorunzhyi}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app 
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ./:/app/
      - ~/.config/gcloud:/home/${USER_NAME}/.config/gcloud
      - $SSH_AUTH_SOCK:/ssh-agent
    ports:
      - 8888:8888
    ipc: host
    init: true