version: '3.8'

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-khorunzhyi}"
    image: pytorch_end_to_end-template
    container_name: pytorch_end_to_end-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-khorunzhyi}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app 
    volumes:
      - ./:/app/
      - ~/.config/gcloud:${HOME}/.config/gcloud
    ports:
      - 8080:8080

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    
    ipc: host
    init: true